version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - misspell

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(codeberg.org/ApoZero/voxel-server-go)
      custom-order: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  misspell:
    locale: US
